ansible_remote_user: ubuntu
postgresql_databases:
  - name: wines
postgresql_users:
  - name: wines_user
    password: "{{ secret_psql_password }}"
git_repo: "https://github.com/Tipuch/wines.git"
git_branch: master
project_name: wines
project_path: "/home/{{ ansible_remote_user }}/{{ project_name }}"
application_log_file: "{{ project_path }}/{{ project_name }}.log"
project_user: "{{ ansible_remote_user }}"
secret_key: "{{ secret_secret_key }}"
domain_name: winecollections.ca

nginx_user: www-data
nginx_group: www-data
nginx_certificate: "{{ secret_nginx_certificate }}"
nginx_key: "{{ secret_nginx_key }}"
nginx_certificate_path: "/etc/nginx/{{ domain_name }}.pem"
nginx_key_path: "/etc/nginx/{{ domain_name }}.key"
nginx_remove_default_vhost: yes

nginx_vhosts:
  - listen: "443 ssl http2"
    server_name: "{{ domain_name }}"
    server_name_redirect: "www.{{ domain_name }}"
    state: "present"
    extra_parameters: |
      ssl_certificate {{ nginx_certificate_path }};
      ssl_certificate_key {{ nginx_key_path }};

      location / {
        proxy_pass https://127.0.0.1:8080;
      }
  - listen: "443 ssl http2 default_server"
    state: "present"
    server_name: "_"
    extra_parameters: |
      ssl_certificate {{ nginx_certificate_path }};
      ssl_certificate_key {{ nginx_key_path }};

      return 404;
