---
- name: Install necessary packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - libssl-dev
    - pkg-config
- stat:
    path: /usr/local/bin/rustc
  register: rust_installed
  tags:
    - rust
- name: Cleanup old Rust installer
  file:
    path: "{{ rust_installer_path }}"
    state: absent
  when: upgrade_rust|bool
  tags:
    - rust
- name: Uninstall old Rust version
  command: "/root/.cargo/bin/rustup self uninstall -y"
  when: upgrade_rust|bool
  tags:
    - rust
- name: Download Rust installer
  get_url:
    url: https://sh.rustup.rs
    dest: "{{ rust_installer_path }}"
    mode: 0700
  when: not rust_installed.stat.exists or upgrade_rust|bool
  tags:
    - rust
- name: Install Rust
  command: "{{ rust_installer_path }} -y"
  when: not rust_installed.stat.exists or upgrade_rust|bool
  tags:
    - rust
- name: Project setup
  import_tasks: project.yml
- name: Supervisord setup
  import_tasks: supervisor.yml
- name: Nginx ssl certificate setup
  copy:
    content: "{{ nginx_certificate }}"
    dest: "{{ nginx_certificate_path }}"
    owner: "{{ project_user }}"
    group: "{{ nginx_group }}"
    mode: 0644
  tags: deploy
  notify: restart application
- name: Nginx ssl key setup
  copy:
    content: "{{ nginx_key }}"
    dest: "{{ nginx_key_path }}"
    owner: "{{ project_user }}"
    group: "{{ nginx_group }}"
    mode: 0660
  no_log: true
  tags: deploy
  notify: restart application
- name: Copy cron script
  template:
    src: crawl_saq.j2
    dest: "/home/{{ project_user }}/crawl_saq.sh"
    mode: 0770
    owner: "{{ project_user }}"
# every monday at 4:00 a.m
- name: Set up crawl cron
  cron:
    name: crawl saq
    hour: 4
    minute: 0  
    weekday: 1
    job: "/home/{{ project_user }}/crawl_saq.sh"
    state: present
